// Deliberate package surface. Adding a symbol here is an API decision, not a side-effect of creating it.
export { resolveClosure, resolveClosurePaths } from './closure.js';
export type { ClosureOptions, ClosureResult, ReferenceEdge } from './closure.js';
export { findInstruction, renderContext, renderPrompt } from './compiler.js';
export type { PromptOptions } from './compiler.js';
export { CONFIG_FILE_YAML, CONFIG_FILE_YML, CONFIG_INSTRUCTION, findConfig, findProjectRoot, loadConfig, saveConfig } from './config.js';
export type { ConfigData } from './config.js';
export { collectExpectations, compareExpectations, formatFindings } from './conform.js';
export type { Expectation, Finding, FindingKind } from './conform.js';
export { availableTargets, collectConstraints, collectImports, findEmitTemplate, matchesGlob, planEmit, renderArtifact, renderHole, selectEmitter, splitName } from './emit.js';
export type { EmitPlan, EmitSkip, EmitUnit, HoleOptions } from './emit.js';
export { draftSpec, extractMap } from './extract.js';
export type { ExtractMap } from './extract.js';
export { readGitSnapshot, repositoryPath, toGitPath } from './git.js';
export type { GitSnapshot } from './git.js';
export { findUnreviewedBlocks } from './provenance.js';
export type { BlockProvenance } from './provenance.js';
// Project-file operations remain public for CLI and integration consumers; writes are atomic.
export { HINTBOOKS_FOLDER, URL_FILE_PREFIX, URL_NPM_PREFIX, isPathExists, isPathFolder, readFile, writeFile } from './helper.js';
export { RUNNING_AUTHORING, RUNNING_CONFIG, RUNNING_SYSTEM, emitPacks, isEmitPack, loadHintbook, loadHintbooks, resolveHintbookPaths, resolveHintbookVersion, vocabularyBooks } from './hintbook.js';
export type { HintbookData, InstructionData, MetaData } from './hintbook.js';
export { LOCK_VERSION, collectFileNodes, computeDrift, effectiveFileHashes, formatDrift, hashFileBlocks, hashTargetFile, hashTargetFiles, loadLock, pruneFreshHints, saveLock, selectFreshTargets } from './lock.js';
export type { BlockDiff, BlockHashes, FileDrift, FileDriftStatus, FileHash, LockData, LockEntry } from './lock.js';
export { formatLintFinding, lintHintFiles, nearestKeyword } from './lint.js';
export type { LintFinding } from './lint.js';
export { inspectHoles, mergeArtifact, readPreamble } from './merge.js';
export type { Hole, HoleState, MergeResult, Region } from './merge.js';
export { collectIncludedPaths, collectScopeNodes, countScopes, findHints, listHintFiles, parseHintFile, parseHintFiles, parseHints } from './parser.js';
export type { HintData, HintFileData, ScopeNode } from './parser.js';
export { HINT_EXT, findNearestFolderHint, hintTargetName, isFolderHintPath, matchedNothing, resolveRequests, resolvedNothing } from './resolve.js';
export type { PathRequest, RequestStatus, Resolution } from './resolve.js';
export { searchHints } from './search.js';
export type { SearchOptions, SearchResult } from './search.js';
export { collectContractScopes, formatStaleness, measureStaleness } from './staleness.js';
export type { ScopeInput, ScopeStaleness } from './staleness.js';
export { renderTemplate } from './template.js';
export { countFindings, countPending, formatStatus, inspectProject } from './status.js';
export type { StatusEntry, StatusKind, StatusReport } from './status.js';
export { parseSymbols, readSymbols } from './symbols.js';
export type { AdapterReading, CodeSymbol, SymbolMember, SymbolReading } from './symbols.js';
export { collectSurfaces, countSurfaceKeywords, formatVerification, verifyTargets } from './verify.js';
export type { FileVerification, Surface, VerifyStatus } from './verify.js';
